import { createFileRoute } from '@tanstack/react-router';
import { useState, useRef } from 'react';
import { Search, Bookmark, SlidersHorizontal, ChevronDown, ChevronLeft, ChevronRight, Play, Info, Plus, Check, Star, ArrowRight, Sparkles, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { featured, movies, networks, type Movie } from '@/lib/movies';

export const Route = createFileRoute('/')({
 head:()=>({meta:[{title:'MultiMovies — Movies, Series & More'},{name:'description',content:'Explore movies, discover series, and find your next favourite across popular streaming networks.'},{property:'og:title',content:'MultiMovies — Movies, Series & More'},{property:'og:description',content:'Your next favourite movie or series is waiting. Browse the latest titles and featured collections.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
 component:Index,
});
const menus:Record<string,string[]>={Genre:['Action','Adventure','Animation','Comedy','Crime','Drama','Horror','Thriller'],Category:['All titles','Movies','Series'],OTT:networks.map(n=>n.name),'Gen Z':['Animation','Adventure','Comedy'],Collection:['All titles','Action','Adventure','Thriller']};
function Index(){
 const [slide,setSlide]=useState(0);const [menu,setMenu]=useState<string|null>(null);const [searchOpen,setSearchOpen]=useState(false);const [query,setQuery]=useState('');const [selected,setSelected]=useState<Movie|null>(null);const [episodes,setEpisodes]=useState(false);const [saved,setSaved]=useState<string[]>([]);const [listOnly,setListOnly]=useState(false);const [filter,setFilter]=useState('All titles');const [tab,setTab]=useState('All');const [filtersOpen,setFiltersOpen]=useState(false);const [expanded,setExpanded]=useState(false);
 const catalogRef=useRef<HTMLElement>(null);const hero=featured[slide]??featured[0];
 const toggleSave=(id:string)=>setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const chooseFilter=(value:string)=>{setFilter(value);setMenu(null);setListOnly(false);setTab('All');catalogRef.current?.scrollIntoView({behavior:'smooth',block:'start'});};
 const openMovie=(movie:Movie,showEpisodes=false)=>{setSelected(movie);setEpisodes(showEpisodes);};
 const allMovies=[...featured,...movies];const results=allMovies.filter(m=>m.title.toLowerCase().includes(query.toLowerCase()));
 const visible=(listOnly?allMovies.filter(m=>saved.includes(m.id)):movies).filter(m=>(tab==='All'||m.type===(tab==='Movies'?'Movie':'Series'))&&(filter==='All titles'||m.genre===filter||m.network===filter||m.type===(filter==='Movies'?'Movie':filter==='Series'?'Series':filter)));
 const next=(direction:number)=>setSlide(prev=>(prev+direction+featured.length)%featured.length);
 return <>
 <header className="site-header">
  <a href="/" className="wordmark" aria-label="MultiMovies home"><span>MULTI</span><b>MOVIES</b></a>
  <nav className="nav-pill" aria-label="Main navigation"><Button variant="ghost" className={`nav-control ${filter==='All titles'?'active':''}`} onClick={()=>{setFilter('All titles');setListOnly(false);setMenu(null);window.scrollTo({top:0,behavior:'smooth'});}}>Home</Button>{Object.keys(menus).map(label=><div className="nav-group" key={label}><Button variant="ghost" className="nav-control" aria-expanded={menu===label} onClick={()=>setMenu(menu===label?null:label)}>{label}<ChevronDown/></Button>{menu===label&&<div className="nav-dropdown">{menus[label]?.map(item=><Button key={item} variant="ghost" className="nav-item" onClick={()=>chooseFilter(item)}>{item}</Button>)}</div>}</div>)}<Button variant="ghost" className="nav-control" onClick={()=>{setSelected(null);setMenu(menu==='SOS'?null:'SOS');}}>SOS<ChevronDown/></Button>{menu==='SOS'&&<div className="nav-dropdown"><span className="p-3 text-xs text-muted-foreground">For enquiries: contact@multimovies.garden</span></div>}</nav>
  <div className="header-tools"><Button variant="ghost" size="icon" className="round-control" aria-label="Search movies and series" title="Search" onClick={()=>setSearchOpen(true)}><Search/></Button><Button variant="ghost" size="icon" className="round-control" aria-label="My list" title="My list" onClick={()=>{setListOnly(!listOnly);setFilter('All titles');catalogRef.current?.scrollIntoView({behavior:'smooth'});}}><Bookmark className={listOnly?'text-brand':''}/></Button><Button variant="ghost" size="icon" className="round-control" aria-label="Browse filters" title="Browse filters" onClick={()=>{setFiltersOpen(!filtersOpen);catalogRef.current?.scrollIntoView({behavior:'smooth'});}}><SlidersHorizontal/></Button><Button variant="ghost" size="icon" className="round-control mobile-menu" aria-label="Open menu" onClick={()=>setMenu(menu==='mobile'?null:'mobile')}><Menu/></Button></div>
  {menu==='mobile'&&<div className="nav-dropdown mobile-dropdown">{['All titles','Movies','Series','Action','Animation','Horror'].map(x=><Button key={x} variant="ghost" className="nav-item" onClick={()=>chooseFilter(x)}>{x}</Button>)}</div>}
 </header>
 <main>
 <section className="hero" aria-label="Featured titles"><img key={hero.id} className="hero-art" src={hero.image} alt={hero.title}/><div className="hero-inner"><div className="eyebrow">Latest updates</div><h1>{hero.title}</h1><div className="movie-meta"><span>{hero.year}</span><span>{hero.type}</span><span>{hero.genre}</span><span className="quality">1080p</span></div><p className="hero-description">{hero.description}</p><div className="hero-actions"><Button className="cinema-cta" onClick={()=>openMovie(hero,true)}><Play/>{hero.type==='Series'?'Explore episodes':'Explore movie'}</Button><Button variant="secondary" className="cinema-cta hero-secondary" onClick={()=>openMovie(hero)}><Info/>More info</Button><Button variant="ghost" size="icon" className="round-control" aria-label={saved.includes(hero.id)?'Remove featured title from list':'Add featured title to list'} title="Add to my list" onClick={()=>toggleSave(hero.id)}>{saved.includes(hero.id)?<Check/>:<Plus/>}</Button></div><div className="carousel-bottom"><div className="slide-count">0{slide+1}<small>/ 03</small></div><div className="slide-markers">{featured.map((m,i)=><Button key={m.id} variant="ghost" className={`slide-marker ${slide===i?'selected':''}`} aria-label={`Show ${m.title}`} onClick={()=>setSlide(i)}/>)}</div><div className="slide-arrows"><Button variant="ghost" size="icon" className="round-control" aria-label="Previous featured title" onClick={()=>next(-1)}><ChevronLeft/></Button><Button variant="ghost" size="icon" className="round-control" aria-label="Next featured title" onClick={()=>next(1)}><ChevronRight/></Button></div></div></div></section>
 <div className="content-shell"><section className="network-section"><div className="section-heading"><h2>Browse by network</h2><span className="sub-label">All your favourites, in one place</span></div><div className="network-grid">{networks.map(n=><Button key={n.name} variant="ghost" className={`network-card ${filter===n.name?'selected':''}`} onClick={()=>chooseFilter(n.name)}><img src={n.image} alt={n.name}/><span>{n.name}<ChevronRight/></span></Button>)}</div></section>
 <div className="discovery-banner"><div className="discovery-message"><Sparkles/><div><strong>A world of stories. One destination.</strong><p>Discover movies, binge-worthy series, and everything in between.</p></div></div><Button variant="ghost" className="banner-link" onClick={()=>{setExpanded(true);chooseFilter('All titles');}}>Explore library<ArrowRight/></Button></div>
 <section className="catalog-section" ref={catalogRef}><div className="section-heading"><div className="flex items-center gap-3"><h2>{listOnly?'My list':filter!=='All titles'?filter:'Featured selections'}</h2>{filter!=='All titles'&&<Button variant="ghost" size="icon" className="h-6 w-6" aria-label="Clear filter" onClick={()=>setFilter('All titles')}><X/></Button>}</div><div className="catalog-tabs">{['All','Movies','Series'].map(t=><Button key={t} variant="ghost" className={`tab ${tab===t?'selected':''}`} onClick={()=>setTab(t)}>{t}</Button>)}</div></div>{filtersOpen&&<div className="filter-strip">{['All titles',...menus.Genre].map(f=><Button key={f} variant={filter===f?'secondary':'outline'} className="filter-chip" onClick={()=>setFilter(f)}>{f}</Button>)}</div>}
 <div className="poster-grid">{visible.slice(0,expanded||listOnly?12:6).map(m=><article key={m.id} className="poster-card"><Button variant="ghost" className="poster-button" aria-label={`Details for ${m.title}`} onClick={()=>openMovie(m)}><img src={m.image} alt={m.title} loading="lazy"/><span className="poster-badge">{m.type==='Series'?'SERIES':'MOVIE'}</span><span className="poster-rating"><Star/>{m.rating}</span></Button><Button variant="ghost" size="icon" className={`round-control poster-save ${saved.includes(m.id)?'saved':''}`} aria-label={`${saved.includes(m.id)?'Remove':'Save'} ${m.title}`} title={saved.includes(m.id)?'Remove from my list':'Add to my list'} onClick={()=>toggleSave(m.id)}>{saved.includes(m.id)?<Check/>:<Plus/>}</Button><h3>{m.title}</h3><div className="poster-subtitle"><span>{m.year}</span><i/><span>{m.genre}</span><i/><span>HD</span></div></article>)}</div>{visible.length===0&&<div className="empty-state">{listOnly?'Your list is waiting for its first favourite.':'No titles found. Try another category.'}</div>}
 </section>
 {!listOnly&&filter==='All titles'&&!expanded&&<section className="catalog-section"><div className="section-heading"><h2>Fresh on your radar <span className="sub-label">The latest worth watching</span></h2><Button variant="ghost" className="view-all" onClick={()=>setExpanded(true)}>View all<ArrowRight/></Button></div><div className="poster-grid">{movies.slice(6).filter(m=>tab==='All'||m.type===(tab==='Movies'?'Movie':'Series')).map(m=><article key={m.id} className="poster-card"><Button variant="ghost" className="poster-button" aria-label={`Details for ${m.title}`} onClick={()=>openMovie(m)}><img src={m.image} alt={m.title} loading="lazy"/><span className="poster-badge">{m.type.toUpperCase()}</span><span className="poster-rating"><Star/>{m.rating}</span></Button><Button variant="ghost" size="icon" className={`round-control poster-save ${saved.includes(m.id)?'saved':''}`} aria-label={`Save ${m.title}`} onClick={()=>toggleSave(m.id)}>{saved.includes(m.id)?<Check/>:<Plus/>}</Button><h3>{m.title}</h3><div className="poster-subtitle"><span>{m.year}</span><i/><span>{m.genre}</span><i/><span>HD</span></div></article>)}</div></section>}
 <footer className="site-footer"><div className="footer-inner"><a className="wordmark" href="/" aria-label="MultiMovies home"><span>MULTI</span><b>MOVIES</b></a><p>© 2026 MultiMovies. For the love of stories.</p><div className="footer-links"><span>Movies</span><span>Series</span><span>Discover</span></div></div></footer>
 </div></main>
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogTitle>Find your next favourite</DialogTitle><DialogDescription>Movies, series, and stories worth discovering.</DialogDescription><div className="search-field"><Search className="size-4 text-muted-foreground"/><input aria-label="Search titles" placeholder="Search movies and series…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<Button variant="ghost" size="icon" className="h-6 w-6" aria-label="Clear search" onClick={()=>setQuery('')}><X/></Button>}</div><div className="search-results">{results.map(m=><Button variant="ghost" className="search-result" key={m.id} onClick={()=>{setSearchOpen(false);openMovie(m);}}><img src={m.image} alt=""/><span><strong>{m.title}</strong><small>{m.year} · {m.type} · {m.genre}</small></span><ChevronRight className="ml-auto"/></Button>)}{results.length===0&&<div className="empty-state">No titles match “{query}”.</div>}</div></DialogContent></Dialog>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="details-dialog">{selected&&<><img className={`detail-art ${selected.id.startsWith('movie')?'portrait':''}`} src={selected.image} alt={selected.title}/><div className="detail-content"><DialogTitle>{selected.title}</DialogTitle><div className="movie-meta mt-4"><Star className="size-3 text-rating"/><span>{selected.rating}</span><span>{selected.year}</span><span>{selected.type}</span><span className="quality">1080p</span></div><DialogDescription>{selected.description}</DialogDescription><div className="flex gap-2"><Button className="cinema-cta" onClick={()=>toggleSave(selected.id)}>{saved.includes(selected.id)?<Check/>:<Plus/>}{saved.includes(selected.id)?'Added to my list':'Add to my list'}</Button>{selected.type==='Series'&&<Button variant="secondary" className="cinema-cta" onClick={()=>setEpisodes(!episodes)}><Play/>{episodes?'Hide episodes':'Episodes'}</Button>}</div>{episodes&&selected.type==='Series'&&<div className="episode-list">{['A new beginning','An unexpected turn','Everything changes'].map((name,i)=><div key={name} className="episode"><span>{String(i+1).padStart(2,'0')} &nbsp; {name}</span><small>Episode preview</small></div>)}</div>}</div></>}</DialogContent></Dialog>
 </>;
}
